num1 = int(input("Введите число n: "))
print("    _~_    " * num1)
print("   (o o)   " * num1)
print("  /  V  \  " * num1)
print(" /(  _  )\ " * num1)
print("   ^^ ^^   " * num1)

num2 = int(input("Введите число n: "))
print(" (\__/) "*num2)
print(" (='.'=)"*num2)
print(' (")_(")'*num2)
num3 = int(input("Введите число n: "))
print(" ~ ~ ~ ~ ~ ~ ~ ~"*num3)
print(" ~ ~ _,,,_  ~ ~ ~ ~"*num3)
print(" ~ <°)3333><(~ ~"*num3)
print(" ~ ~ \"?'''? ~ ~ ~"*num3)
num4 = int(input("Введите число n: "))
print("~ ~ ~ ~ ~ ~ ~ ~"*num4)
print("~ ~ ~ ~ ~ ~ ~ ~"*num4)
print("~ ~ ><((((o> ~ ~"*num4)
print("~ ~ ~ ~ ~ ~ ~ ~"*num4)
print("~ ~ ~ ~ ~ ~ ~ ~"*num4)
num5 = int(input("Введите число n: "))
print("``@..@"*num5)
print("`(_____)"*num5)
print("(>____<)"*num5)
print("^^~~~~^^"*num5)